# Generated by Django 5.1.7 on 2025-04-20 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_alter_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='AppointmentTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.appointment')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.ManyToManyField(through='webapp.AppointmentTimeSlot', to='webapp.timeslot'),
        ),
    ]
