# Generated by Django 5.1.7 on 2025-04-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_remove_appointment_appointment_time_timeslot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmenttimeslot',
            unique_together={('time_slot', 'date')},
        ),
    ]
