# Generated by Django 5.1.7 on 2025-04-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_alter_appointmenttimeslot_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='special_type',
            field=models.CharField(blank=True, choices=[('MORNING', 'Whole Morning (8AM-12PM)'), ('AFTERNOON', 'Whole Afternoon (2PM-5PM)'), ('DAY', 'Whole Day (8AM-5PM)')], max_length=20, null=True),
        ),
    ]
